e=6
f=5.4
c="Lalith"
d=True
print(type(e),type(f),type(c),type(d))
a=int(input())
b=int(input())
print("\nArthematic Operators:\n")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print("\nRelational Operators:\n")
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)
print("\nBitwise Operators:\n")
print(a>>1)
print(b<<1)
print(a&b)
print(a|b)
print(a^b)
print("\nLogical Operators\n")
print(a>b and b<a)
print(a>b or b<a)
print(not(a>b))
